version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx
    container_name: magnificentfox_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d

volumes:
  static_volume:
  media_volume:
