version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: magnificentfox-app
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
