version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    container_name: magnificentfox_frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx
    container_name: magnificentfox_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d

volumes:
  static_volume:
  media_volume:
